libvata2: Nfa Struct Reference
Nfa Struct Reference
An NFA.
#include <nfa.hh>
Classes
struct const_iterator
number of transitions; has linear time complexity
Public Member Functions
void add_initial (State state)
void add_initial (const std::vector< State > vec)
bool has_initial (State state) const
void add_final (State state)
void add_final (const std::vector< State > vec)
bool has_final (State state) const
void add_trans (const Trans &trans)
void add_trans (State src, Symbol symb, State tgt)
bool has_trans (const Trans &trans) const
bool has_trans (State src, Symbol symb, State tgt) const
bool trans_empty () const
size_t trans_size () const
const_iterator begin () const
const_iterator end () const
const PostSymb & operator[] (State state) const
const PostSymb * post (State state) const
StateSet post (const StateSet &macrostate, Symbol sym) const
gets a post of a set of states over a symbol
Public Attributes
std::set< State > initialstates = {}
std::set< State > finalstates = {}
Detailed Description
An NFA.
Definition at line 221 of file nfa.hh.
Member Function Documentation
void add_final (State state) inline
Definition at line 244 of file nfa.hh.
References Nfa::finalstates.
Referenced by Nfa::add_final().
void add_final (const std::vector< State > vec) inline
Definition at line 245 of file nfa.hh.
References Nfa::add_final().
void add_initial (State state) inline
Definition at line 235 of file nfa.hh.
References Nfa::initialstates.
Referenced by Nfa::add_initial().
void add_initial (const std::vector< State > vec) inline
Definition at line 236 of file nfa.hh.
References Nfa::add_initial().
void add_trans (const Trans & trans)
Referenced by Nfa::add_trans().
void add_trans (State src, Symbol symb, State tgt) inline
Definition at line 256 of file nfa.hh.
References Nfa::add_trans().
const_iterator begin () const inline
Definition at line 300 of file nfa.hh.
References Nfa::const_iterator::for_begin().
const_iterator end () const inline
Definition at line 301 of file nfa.hh.
References Nfa::const_iterator::for_end().
bool has_final (State state) const inline
Definition at line 250 of file nfa.hh.
References Nfa::finalstates, and Vata2::util::haskey().
bool has_initial (State state) const inline
Definition at line 240 of file nfa.hh.
References Vata2::util::haskey(), and Nfa::initialstates.
bool has_trans (const Trans & trans) const
Referenced by Nfa::has_trans().
bool has_trans (State src, Symbol symb, State tgt) const inline
Definition at line 262 of file nfa.hh.
References Nfa::has_trans().
const PostSymb& operator[] (State state) const inline
Definition at line 303 of file nfa.hh.
References Vata2::Nfa::EMPTY_POST, and Nfa::post().
const PostSymb* post (State state) const inline
Definition at line 314 of file nfa.hh.
Referenced by Nfa::operator[]().
StateSet post (const StateSet & macrostate, Symbol sym) const
gets a post of a set of states over a symbol
bool trans_empty () const inline
Definition at line 267 of file nfa.hh.
size_t trans_size () const
Member Data Documentation
std::set<State> finalstates = {}
Definition at line 233 of file nfa.hh.
Referenced by Nfa::add_final(), and Nfa::has_final().
std::set<State> initialstates = {}
Definition at line 232 of file nfa.hh.
Referenced by Nfa::add_initial(), and Nfa::has_initial().
The documentation for this struct was generated from the following file:
/home/travis/build/ondrik/libvata2/include/vata2/nfa.hh